networks:
  local:
    driver: bridge
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PAMPS_DB_uri: "postgresql://postgres:postgres@db:5432/${PAMPS_DB:-pamps}"
      PAMPS_DB_connect_args: "{}"
    volumes:
      - .:/home/app/api
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - local
  db:
    build: postgres
    image: pamps_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/pamps_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DBS=pamps, pamps_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - local
  pgadmin:
    image: dpage/pgadmin4
    container_name: pamps_pgadmin
    depends_on:
      - db
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pamps@mail.com
      PGADMIN_DEFAULT_PASSWORD: pamps
    networks:
      - local
